### PR TITLE
[Main] Introduce dynamic colors

### PR DESCRIPTION
**Pull request by nexpid**
adds a `__vendetta_syscolors` property to `window`, and a `syscolors: { prop: "__vendetta_syscolors" }` property to `window.__vendetta_loader.features`

please lmk if/when this PR is ready to merge so I can remove the installation guide in readme

### CODE REVIEW

**Comment by nexpid** [comment]
sorry for the commit spam lmao

**Comment by wingio** [comment]
Please remove Gson, we already have kotlinx serialization

**Comment by nexpid** [comment]
ah ok im new to kotlin lmao

**Comment by nexpid** [comment]
should be fine now

**Comment by wingio** [comment]
Can you clarify in the README that the instructions are for testing locally, also can you remove any references to your fork and instead refer to the actions build in this repo

**Comment by nexpid** [comment]
> Can you clarify in the README that the instructions are for testing locally, also can you remove any references to your fork and instead refer to the actions build in this repo

i reverted the README, is it ready to merge now? (squash and merge would be ideal lol)
i could also make a PR at https://github.com/Vendetta-mod/Vendetta to implement the syscolors property into metro itself, instead of just reading from window.__vendetta_syscolors

**Pull request merged**
